project_id = "fgoyvsnsoheboywgtgvi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovableproject.com"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false

[auth.email]

[db]
enabled = true
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54321

[edge-runtime]
policy = "oneshot"

[functions.verify-payment]
verify_jwt = true

[functions.generate-daily-quote]
verify_jwt = false

[functions.marketing-email]
verify_jwt = false

[functions.daily-streak-update]
verify_jwt = false

[functions.athena-coach]
verify_jwt = true

[functions.create-payment]
verify_jwt = false

[functions.verify-apple-purchase]
verify_jwt = true

[functions.suggest-items]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false